# Generated by Django 6.0 on 2025-12-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip_code'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'slug'], name='search_product_idx'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='store_products',
        ),
    ]
