# Generated by Django 6.0 on 2025-12-18 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('view_history_info', 'Can view customer history info')]},
        ),
    ]
